# Generated by Django 5.2.8 on 2025-11-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Проведенных проверок')),
                ('corporate_clients', models.PositiveIntegerField(default=0, verbose_name='Корпоративных клиентов')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Лет на рынке')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика сайта',
                'verbose_name_plural': 'Статистика сайта',
            },
        ),
    ]
