# Generated by Django 5.2.8 on 2025-12-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitestatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Политика конфиденциальности', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст политики')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
        migrations.CreateModel(
            name='ResearchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О наших исследованиях', help_text='Заголовок блока, например: "Почему выбирают нас"', max_length=200, verbose_name='Заголовок блока')),
                ('column_1', models.TextField(blank=True, help_text='Текст для первой колонки. Можно использовать HTML: &lt;strong&gt;жирный текст&lt;/strong&gt;, &lt;br&gt; - перенос строки, &lt;ul&gt;&lt;li&gt;список&lt;/li&gt;&lt;/ul&gt;', verbose_name='Колонка 1 (левая)')),
                ('column_2', models.TextField(blank=True, help_text='Текст для второй колонки. Можно использовать HTML: &lt;strong&gt;жирный текст&lt;/strong&gt;, &lt;br&gt; - перенос строки, &lt;ul&gt;&lt;li&gt;список&lt;/li&gt;&lt;/ul&gt;', verbose_name='Колонка 2 (средняя)')),
                ('column_3', models.TextField(blank=True, help_text='Текст для третьей колонки. Можно использовать HTML: &lt;strong&gt;жирный текст&lt;/strong&gt;, &lt;br&gt; - перенос строки, &lt;ul&gt;&lt;li&gt;список&lt;/li&gt;&lt;/ul&gt;', verbose_name='Колонка 3 (правая)')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, чтобы блок отображался на главной странице', verbose_name='Показывать на сайте')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше блок. Используется при наличии нескольких блоков', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Блок "Об исследованиях" (3 колонки)',
                'verbose_name_plural': 'Блоки "Об исследованиях" (3 колонки)',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SiteStatistics',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cache_version',
            field=models.IntegerField(default=0),
        ),
    ]
