# Generated by Django 5.2.8 on 2025-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, choices=[('user-shield', 'Защита пользователя'), ('briefcase', 'Портфель - бизнес'), ('users', 'Группа людей'), ('search', 'Поиск - расследования'), ('shield-alt', 'Щит - безопасность'), ('eye', 'Глаз - наблюдение'), ('file-contract', 'Документ - проверка'), ('balance-scale', 'Весы - справедливость'), ('id-card', 'ID карта - персонал'), ('lock', 'Замок - конфиденциальность')], default='user-shield', help_text='Выберите иконку для услуги', max_length=50, verbose_name='Иконка'),
        ),
    ]
